pipeline:
  name: Build MyFirstRepo
  identifier: Build_Aravinfree_MyFirstRepo_1743013975881
  projectIdentifier: Project_1122
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    connectorRef: DockerConnector
                    image: hello
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: Kubectl
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1718540861981
        repoName: Aravinfree/MyFirstRepo
        build: <+input>
